name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: true

jobs:
  build-and-test:
    name: Build and Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["18.x", "20.x", "lts/*"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm 10.11.0
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm build

      - name: Run all tests
        run: pnpm test

  lint-and-format:
    name: Lint and Format (SDK)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm 10.11.0
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint SDK package
        run: pnpm -F @aptos-labs/script-composer-sdk lint

      - name: Format check SDK package
        run: pnpm -F @aptos-labs/script-composer-sdk fmt:check

  examples-build:
    name: Build Example Projects (Next.js & React)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm 10.11.0
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build example projects
        run: |
          # Build all workspace packages under examples/** that define a "build" script
          pnpm build